# Generated by Django 4.2.2 on 2023-06-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='telephone',
            field=models.CharField(max_length=11, unique=True, verbose_name='Телефон'),
        ),
    ]
